config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts

  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, foreign_key: 'owner_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.owner = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

private
  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p>
  <%= link_to 'Home', root_path %>
</p>
<p>  
  <% if user_signed_in? %>
    Welcome, <%= current_user.email %>.
    <%= link_to 'Logout', destroy_user_session_path %>
  <% else %>
    <%= link_to 'Login', new_user_session_path %> |
    <%= link_to 'Register', new_user_registration_path %>
  <% end %>
</p>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>My Blog</h1>

<% @posts.each do |post| %>
  <div class="post">
    <h3><%= post.title %></h3>
    <p><%= post.description.truncate(100, separator: ' ') %></p>
    <%= link_to 'Show', post %>
  </div>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'New post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div> 
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <br>
    <%= f.text_area :description %>
  </div>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <%= @post.description %>
</p>

<%= link_to 'Rent', rent_post_path(post), method: :patch, remote: true %>